Config:
  url: "https://api.openai.com/v1/chat/completions"
  instructions: "You are a helpful assistant in Minecraft. Respond concisely and friendly."
  apikey: ""
  model: "gpt-4o-mini"
  googleapi: false