main: com.ramide1.mcllm.App
name: mcllm
version: 1.0
api-version: 1.21.8
commands:
  llm:
    description: Answer a question with llm
    permission: mcllm.llm
  llmreload:
    description: Reload llm configuration
    permission: mcllm.llmreload