main: com.ramide1.mcgpt.App
name: mcgpt
version: 1.0
api-version: 1.20
commands:
  gpt:
    description: Answer a question with gpt
    permission: mcgpt.gpt
  gptreload:
    description: Reload gpt config
    permission: mcgpt.gptreload